command:
  - "streamlit"
  - "run"
  - "main.py"
env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/148ccb90800933a1
