# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %pip install databricks-automl-runtime -q
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

spark.sql("USE CATALOG `mk_fiddles`")
spark.sql("USE SCHEMA `detroit_911`")

# COMMAND ----------

df = spark.sql("SELECT * FROM incidents_forecasting_gold ORDER BY council_district, priority, called_at_hour")
display(df)

# COMMAND ----------

# MAGIC %sql
# MAGIC with horizon as (
# MAGIC   SELECT 
# MAGIC     date_add(max(called_at_hour), 3) as forecast_horizon
# MAGIC   FROM incidents_forecasting_gold
# MAGIC )
# MAGIC SELECT
# MAGIC   *
# MAGIC FROM AI_FORECAST(
# MAGIC   TABLE(incidents_forecasting_gold),
# MAGIC   horizon => (SELECT forecast_horizon FROM horizon),
# MAGIC   time_col => 'called_at_hour',
# MAGIC   value_col => 'call_count',
# MAGIC   group_col => ('council_district', 'priority'),
# MAGIC   prediction_interval_width => 0.9
# MAGIC )
